### ISSUE TITLE
OS X Build fails

### ISSUE THREAD

**Issue by kittylyst** [oneis/haplo#2]
The OS X (Mavericks) build fails with this trailing output:

    /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
    make[3]: Nothing to be done for `all-am'. 
    Create test certificates...
    cat: target/classpath.txt: No such file or directory

Perhaps the classpath construction hasn't been done, e.g. via:

    mvn -Dmdep.outputFile=target/classpath.txt dependency:build-classpath

**Comment by bensummers** [comment]
This is fixed in cb1806d43014454ab02bb3351e4c9d07075f220f
