### ISSUE TITLE
Install is fragile on OS X

### ISSUE THREAD

**Issue by kittylyst** [oneis/haplo#3]
The installer is somewhat fragile on OS X - it expects a hardcoded path for Postgres, which seems to be only achievable via a source build or an EnterpriseDB installer.

Notably, the standard brew path is not checked, and we are overly sensitive on version numbers.

**Comment by bensummers** [comment]
Unfortunately Mac OS X appears to be a difficult platform for this sort of project. On the web site I've recommended people run Ubuntu in a VM, it's far easier. :-(

**Comment by bensummers** [comment]
Mac OS X builds now use pg_config to pick up the location of the Postgres install.
