### ISSUE TITLE
INSTALL.md is missing

### ISSUE THREAD

**Issue by kittylyst** [oneis/haplo#4]
There's no idiot's guide to getting Haplo built & installed.

My first instinct was to try:
    mvn package

as, hey, there's a pom.xml there. Even a simple installation doc along the lines of: "run fetch-and-compile.sh" (& btw, if you're running on OS X, do these additional things) would be massively helpful. 

If I get an hour over the weekend, I might try to write one...

**Comment by bensummers** [comment]
Thanks!

I have some instructions written up, and they'll be going on the web site, which should be up early next week.

**Comment by bensummers** [comment]
Documentation is now available at http://haplo.org/documentation
