### ISSUE TITLE
Use pg_config to determine postgresql variables

### ISSUE THREAD

**Issue by ruckc** [oneis/haplo#6]
Using pg_config will assist futureproofing haplo configuration, as you won't need to hardcode path variables.

**Comment by bensummers** [comment]
But it still needs to find pg_config ... :-(

I plan on revisiting the build system when I see how people are using this, and the problems they encounter. It's very different trying to make something run anywhere than in a single highly constrained environment.

**Comment by bensummers** [comment]
Implemented in ccce29c4cf0c9b3342743cea888cf8aff6fb983f
