### ISSUE TITLE
Remove hardcoded dependency on Java 1.7

### ISSUE THREAD

**Issue by ruckc** [oneis/haplo#7]
Improve logic in config/load.rb for Java version, to support Java 8, as Java 1.7 EOLs in April 2015.

Improve JAVA_HOME lookup logic, do you really need a JAVA_HOME, or just a java binary (from PATH)?

**Comment by bensummers** [comment]
Commit 5544324d8ecbc9080b31501dcba1c7cc0034f574 now requires Java 8.
